version: '3.7'

services:
    app:
        build:
          context: ./app
          dockerfile: Dockerfile
        command: streamlit run main.py --server.port 80
        ports:
          - 8081:80
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.gtp-laba-3.loadbalancer.server.port=80"
            - "traefik.http.routers.gtp-laba-3.tls.certresolver=le"
            - "traefik.http.routers.gtp-laba-3.rule=Host(`gpt-lab.onixx.ru`)"
            - "traefik.http.routers.gtp-laba-3.entrypoints=websecure"
            - "traefik.http.routers.gtp-laba-3.tls=true"